### ISSUE TITLE
Face processing fails to start

### ISSUE THREAD

**Issue by drcmputr** [codeproject/CodeProject.AI-FaceProcessing#2]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Face processing fails to start.  I get the following error in the logs:

08:35:49:Started Face Processing module
08:35:50:face.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
08:35:50:face.py: GPU in use: NVIDIA GeForce RTX 4090
08:35:50:face.py: Traceback (most recent call last):
08:35:50:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\face.py", line 37, in 
08:35:50:face.py:     from process import YOLODetector
08:35:50:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\.\process.py", line 2, in 
08:35:50:face.py:     import cv2
08:35:50:face.py: ModuleNotFoundError: No module named 'cv2'
08:35:51:Module FaceProcessing has shutdown

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.9.4
 - OS: Windows 11
 - System RAM 64GB
 - GPU (if available) GeForce RTX 4090
 - GPU RAM (if available)  24GB

**Additional context**
I only have Object Detection (YOLOv8) and Face Processing installed.  Does the Face Processing module need something else installed to work?

**Comment by ChrisMaunder** [comment]
Pleased try uninstalling then reinstalling the Face module via the dashboard.

**Comment by drcmputr** [comment]
I just tried that (again) and I have the same issue.  It shows as started, then a minute or two later says "failed to start" with the same errors in the logs.

12:53:10:Started Face Processing module
12:53:10:Installer exited with code 1
12:53:12:face.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
12:53:12:face.py: GPU in use: NVIDIA GeForce RTX 4090
12:53:12:face.py: Traceback (most recent call last):
12:53:12:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\face.py", line 37, in 
12:53:12:face.py:     from process import YOLODetector
12:53:12:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\.\process.py", line 2, in 
12:53:12:face.py:     import cv2
12:53:12:face.py: ModuleNotFoundError: No module named 'cv2'
12:53:12:Module FaceProcessing has shutdown
12:53:12:face.py: has exited
12:53:13:Module FaceProcessing started successfully.

**Comment by drcmputr** [comment]
![image](https://github.com/user-attachments/assets/4521da6a-c3b7-4391-a791-6c5c78a7ca95)

**Comment by ChrisMaunder** [comment]
@drcmputr Please click that 'info' button on the RHS of the Face listing, then scroll down till you see the install log. Can you please cut and paste that here?

**Comment by drcmputr** [comment]
When I click on Info, all it shows is this.  I don't see any install log.

Module 'Face Processing' 1.12.2 (ID: FaceProcessing)
Valid:            True
Module Path:      <root>\modules\FaceProcessing
Module Location:  Internal
AutoStart:        True
Queue:            faceprocessing_queue
Runtime:          python3.7
Runtime Location: Shared
FilePath:         intelligencelayer\face.py
Start pause:      3 sec
Parallelism:      0
LogVerbosity:     
Platforms:        all,!jetson
GPU Libraries:    installed if available
GPU:              use if supported
Accelerator:      
Half Precision:   enable
Environment Variables
   APPDIR             = <root>\modules\FaceProcessing\intelligencelayer
   DATA_DIR           = C:\ProgramData\CodeProject\AI
   MODE               = MEDIUM
   MODELS_DIR         = <root>\modules\FaceProcessing\assets
   PROFILE            = desktop_gpu
   USE_CUDA           = True
   YOLOv5_AUTOINSTALL = false
   YOLOv5_VERBOSE     = false
Status Data:  
Started:      05 Dec 2024 12:53:10 PM Pacific Standard Time
LastSeen:     Not seen
Status:       Started
Requests:     0 (includes status calls)

![image](https://github.com/user-attachments/assets/46ed29f5-ba55-4fc9-ad91-6cc81b220244)

**Comment by ChrisMaunder** [comment]
(I reread your message and noted you saw no install info)

Can you please look for an install.log file in C:\Program FIles\CodeProject\AI\modules\FaceProcessing?

**Comment by drcmputr** [comment]
Here you go:

2024-12-05 12:52:30:              Installing CodeProject.AI Analysis Module                
2024-12-05 12:52:30: ======================================================================
2024-12-05 12:52:30:                    CodeProject.AI Installer                           
2024-12-05 12:52:30: ======================================================================
2024-12-05 12:52:31: 861.3Gb of 1907Gb available on (No label) (Windows 11 x86_64 - windows)
2024-12-05 12:52:31: General CodeProject.AI setup                                          
2024-12-05 12:52:32: Checking for VC++ Redist...v14 Present.
2024-12-05 12:52:33: Creating Directories...done
2024-12-05 12:52:33: GPU support                                                           
2024-12-05 12:52:33: CUDA Present...Yes (CUDA 12.7, cuDNN 9.5, CUDA Toolkit: false)
2024-12-05 12:52:34: Updating path to include cuDNN
2024-12-05 12:52:34: ROCm Present...No
2024-12-05 12:52:34: Checking for .NET 9.0...Checking runtimes...All good. Found .NET aspnetcore 9
2024-12-05 12:52:38: Reading FaceProcessing settings.......done
2024-12-05 12:52:38: Installing module Face Processing 1.12.2                              
2024-12-05 12:52:38: Internal module install
2024-12-05 12:52:38: Installing Python 3.7
2024-12-05 12:52:38: Python 3.7 is already installed
2024-12-05 12:52:39: Creating Virtual Environment (Shared)...Virtual Environment already present
2024-12-05 12:52:39: Confirming we have Python 3.7 in our virtual environment...present
2024-12-05 12:52:41: Downloading Face models...already exists...Expanding...done.
2024-12-05 12:52:41: Copying contents of models-face-pt.zip to assets...done
2024-12-05 12:52:41: Installing Python packages for Face Processing
2024-12-05 12:52:41: [0;Installing GPU-enabled libraries: If available
2024-12-05 12:52:43: Ensuring Python package manager (pip) is installed...done
2024-12-05 12:52:46: Ensuring Python package manager (pip) is up to date...done
2024-12-05 12:52:46: Python packages specified by requirements.windows.cuda.txt
2024-12-05 12:52:48:   - Installing urllib3, the HTTP client for Python...Already installed
2024-12-05 12:52:49:   - Installing Pandas, a data analysis / data manipulation tool...Already installed
2024-12-05 12:52:50:   - Installing CoreMLTools, for working with .mlmodel format models...Already installed
2024-12-05 12:52:51:   - Installing SciPy, a library for mathematics, science, and engineering...Already installed
2024-12-05 12:52:52:   - Installing PyYAML, a library for reading configuration files...Already installed
2024-12-05 12:52:53:   - Installing PyTorch, an open source machine learning framework...Already installed
2024-12-05 12:52:54:   - Installing TorchVision, for working with computer vision models...Already installed
2024-12-05 12:52:55:   - Installing Seaborn, a data visualization library based on matplotlib...Already installed
2024-12-05 12:52:57:   - Installing the CodeProject.AI SDK...Already installed
2024-12-05 12:52:57: Scanning modulesettings for downloadable models...No models specified
2024-12-05 12:53:09: Traceback (most recent call last):
2024-12-05 12:53:09:   File "intelligencelayer/face.py", line 37, in <module>
2024-12-05 12:53:09:     from process import YOLODetector
2024-12-05 12:53:09:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\.\process.py", line 2, in <module>
2024-12-05 12:53:09:     import cv2
2024-12-05 12:53:09: ModuleNotFoundError: No module named 'cv2'
2024-12-05 12:53:10: Self test: Self-test failed
2024-12-05 12:53:10: Module setup time 00:00:35.17
2024-12-05 12:53:10: Setup complete                                                        
2024-12-05 12:53:10: Total setup time 00:00:39.55
2024-12-05 12:53:10: SETUP FAILED:
2024-12-05 12:53:10:  - [FaceProcessing] Self test failed

**Comment by ChrisMaunder** [comment]
I found the problem. Refresh your dashboard and you should see an update for FaceProcessing. Update and it should work

**Comment by drcmputr** [comment]
I wasn't quite sure how to "refresh the dashboard", so I just uninstalled and reinstalled FaceProcessing again and it now works!  Thank you.

![image](https://github.com/user-attachments/assets/b48f0571-3388-4972-9872-1d62f97994ac)

**Comment by ChrisMaunder** [comment]
Perfect. Thanks for hanging in there while I got this sorted.
